name: dart_script
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  args:
  async:
  dart_cli:
    git:
      url: https://github.com/javaddict/dart_cli.git
  dart_console:
  glob:
  path:
  uuid:

dev_dependencies:
  lints:
  test:

executables:
  dart_script:
  dart_cache: